bash pipe/run_chr.sh Chr1A
bash pipe/run_chr.sh Chr1B
bash pipe/run_chr.sh Chr1D
bash pipe/run_chr.sh Chr2A
bash pipe/run_chr.sh Chr2B
bash pipe/run_chr.sh Chr2D
bash pipe/run_chr.sh Chr3A
bash pipe/run_chr.sh Chr3B
bash pipe/run_chr.sh Chr3D
bash pipe/run_chr.sh Chr4A
bash pipe/run_chr.sh Chr4B
bash pipe/run_chr.sh Chr4D
bash pipe/run_chr.sh Chr5A
bash pipe/run_chr.sh Chr5B
bash pipe/run_chr.sh Chr5D
bash pipe/run_chr.sh Chr6A
bash pipe/run_chr.sh Chr6B
bash pipe/run_chr.sh Chr6D
bash pipe/run_chr.sh Chr7A
bash pipe/run_chr.sh Chr7B
bash pipe/run_chr.sh Chr7D
